version: '3.2'
services:
  db:
    container_name: postgres
    image: postgres

  web:
    container_name: elixir
    build: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
