version: '3.2'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: phoenix
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    container_name: elixir
    build: 
        context: ./Dockerfile
    command: /bin/bash docker_start.sh
    volumes:
      - .:/my_app
    ports:
      - "4000:4000"
    depends_on:
      - db
